---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-ShiftPlanning
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 0
  LWP::Protocol::https: 6
  LWP::UserAgent: 6
  Test::More: 0
version: 0.02
